files:
  - source: /src/content/**/**.md
    ignore:
      - /src/content/**/**_pt.md
      - /src/content/**/**_es.md
    translation: /src/content/**/%file_name%_%two_letters_code%.%file_extension%
