name: "Create release on Github"
description: "Downloads all artifacts, generates readme and publishes a release to Github"
inputs:
  pre-release:
    description: "Is this a pre-release: true or false"
  repo_token:
    required: true
    description: "Github repository personal access token"
runs:
  using: "composite"
  steps:
    - name: Download all workflow artifacts
      uses: actions/download-artifact@v3
      with:
        path: "./"
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: "tar"
        filename: "portal.tar.gz"
        path: "/home/runner/work/edt-offline-portal/edt-offline-portal/nuxt-app/*"
    - name: "✏️ Upload imgs and release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ inputs.repo_token }}"
        prerelease: ${{ inputs.pre-release }}
        files: |
          *.tar.gz
