name: "Create release on Docker Hub"
description: "Builds from Dockerfile and creates a release on Docker Hub"
inputs:
  docker-repository:
    required: true
    description: "Docker Hub repository in the format <namespace>/<name>"
  docker-username:
    required: true
    description: "Docker Hub username"
  docker-token:
    required: true
    description: "Docker Hub token"
  short-description:
    description: "A short description about the project"
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        tags: ${{inputs.docker-repository}}:nightly
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{inputs.docker-repository}}
        short-description: ${{inputs.description}}
