name: "Create release on Docker Hub"
description: "Builds from Dockerfile and creates a release on Docker Hub"
inputs:
  docker-repository:
    required: true
    description: "Docker Hub repository in the format <namespace>/<name>"
  docker-file:
    description: "Dockerfile to be used"
    default: "Dockerfile"
  image-tag:
    description: "Docker Hub image tag, defaults to latest"
    default: "latest"
  docker-username:
    required: true
    description: "Docker Hub username"
  docker-token:
    required: true
    description: "Docker Hub token"
  short-description:
    description: "A short description about the project"
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-token }}
    - name: Build and export to Docker
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{inputs.docker-file}}
        load: true
        tags: ${{inputs.docker-repository}}:${{inputs.image-tag}}
    # TODO: add testing
    # - name: Test Docker image
    #   shell: bash
    #   run: |
    #     docker run --rm ${{inputs.docker-repository}}:${{inputs.image-tag}}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{inputs.docker-repository}}:${{inputs.image-tag}}
    - name: Docker Hub Description
      if: ${{inputs.short-description != 'false'}}
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-token }}
        repository: ${{inputs.docker-repository}}
        short-description: ${{inputs.short-description}}
