name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Nuxt
        id: generate-nuxt
        uses: ./.github/actions/generate-nuxt
        with:
          router-base: "/"
  release-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release Docker
        id: release-docker
        uses: ./.github/actions/release-docker
        with:
          docker-repository: communityfirst/edt-offline-portal
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
          short-description: "The portal to the EDT Offline experience"
  release-docker-full:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release Docker
        id: release-docker
        uses: ./.github/actions/release-docker
        with:
          docker-repository: communityfirst/edt-offline-portal
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
          image-tag: full
          docker-file: Dockerfile.full

  github-release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Github release
        uses: ./.github/actions/release-github
        with:
          repo_token: "${{ secrets.PAT }}"
